version: '3.7'
services:
  app:
    container_name: courses-app
    build:
      context: .
      dockerfile: Dockerfile
#    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 180 --workers 3
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    volumes:
      - .:/opt/app
    depends_on:
      - pgsql

  pgsql:
    container_name: courses-db
    image: postgres:12-alpine
    volumes:
      - postgres_data11:/var/lib/postgresql/data/
    environment:
      PGPASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQLL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data11:
  minio_data11:
