# Generated by Django 4.2.3 on 2024-06-11 03:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.IntegerField(choices=[(0, 'На проверке'), (1, 'Не пройдено'), (2, 'Пройдено')], default=0, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.task', verbose_name='Задание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='min_tasks_for_pass',
            field=models.IntegerField(default=0, verbose_name='Мин. Кол-во задач для прохождения'),
            preserve_default=False,
        ),
    ]
