# Generated by Django 4.2.3 on 2024-06-11 08:01

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_task_min_tasks_for_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=courses.models.course_storage, verbose_name='Изображение'),
        ),
    ]
