# Generated by Django 4.2.3 on 2024-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='min_tasks_for_pass',
        ),
        migrations.AddField(
            model_name='course',
            name='min_tasks_for_pass',
            field=models.IntegerField(default=0, verbose_name='Мин. Кол-во задач для прохождения'),
        ),
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
