# Generated by Django 4.2.3 on 2024-06-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_task_min_tasks_for_pass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_body',
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вариант ответа на задание',
                'verbose_name_plural': 'Варианты ответов на задания',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.taskoption', verbose_name='Вариант ответа на задание'),
            preserve_default=False,
        ),
    ]
