# Generated by Django 4.2.3 on 2024-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoption',
            name='correctly',
            field=models.BooleanField(default=False, verbose_name='correctly'),
        ),
    ]
