# Generated by Django 4.2.3 on 2024-06-16 21:51

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_answer_status_alter_taskoption_correctly'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.attachment_upload, verbose_name='Файл'),
        ),
    ]
