# Generated by Django 4.2.3 on 2024-06-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='min_tasks_for_pass',
        ),
    ]
